version: '3.6'

services: 
  # Backend API
  face-recognition-api:
    container_name: backend
    build: ./
    command: npm run dev
    working_dir: /usr/src/face-recognition-api
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/usr/src/face-recognition-api
    environment: 
      CLARIFAIAPIKEY: ${CLARIFAIAPIKEY}
      PORT: ${BACKEND_PORT}
      POSTGRES_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/face-recognition
  # Postgres
  postgres: 
    container_name: postgres
    build: ./postgres
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: face-recognition
      POSTGRES_HOST: postgres
    ports: 
      - "5432:5432"